/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import javax.swing.table.DefaultTableModel;
import restaurante.Codigo.Alimento;
import restaurante.Codigo.ColaAlimento;
import restaurante.Codigo.ListaSPedido;
import restaurante.Codigo.*;

/**
 *
 * @author Tostadora
 */
public class Producto extends javax.swing.JFrame {
   DefaultTableModel modelo;
    /**
     * Creates new form NewJFrame
     */
   private String tipo;
   private ListaSPedido ls = new ListaSPedido();
    public Producto() {
        initComponents();
          
        modelo = new DefaultTableModel();
        modelo.addColumn("Alimento");
        modelo.addColumn("Pracio");
        
        this.tabla.setModel(modelo);
    }

    public String getTipo() {
        return tipo;
    }
    

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    private ColaAlimento cl;
    private ColaMesa cm;

    public ColaMesa getCm() {
        return cm;
    }

    public void setCm(ColaMesa cm) {
        this.cm = cm;
    }
        
    public ColaAlimento getCl() {
        return cl;
    }

    public void setCl(ColaAlimento cl) {
        this.cl = cl;
    }
    private int m;
    private Restaurante res;
    
    public void Base(Restaurante res, String text,int m){
        this.res = res;
        this.tipo = text;
        this.m = m;
        System.out.println("Generando Base");
        cl = res.getCAlimento();
        cm = res.getCMesa(); 
        cargar();
        System.out.println("---------------");
        System.out.println("");
    }
    
    public void cargar(){
        
         String[] v = new String[2];
        ColaAlimento aux = new ColaAlimento();
       
        while(!cl.esVacia()){  
            Alimento al = cl.elicola();
            
           
            
                v[0] = al.getNombre();
                v[1] = String.valueOf(al.getPrecio());
                modelo.addRow(v);
            
            aux.adicola(al);
                       
        }
        aux.mostrarCola();
        cl.vaciarCola(aux);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("Comprar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jButton1)
                        .addGap(36, 36, 36)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int fila = tabla.getSelectedRow();
        String nombre = (String) modelo.getValueAt(fila,0);
        System.out.println(nombre);
        
        ColaAlimento aux = new ColaAlimento();
        
        System.out.println("Comprobando cl");
        System.out.println(cl.esVacia());
        cl.mostrarCola();
        System.out.println("*-*-*-*");
        
        while(!cl.esVacia()){
            Alimento a = cl.elicola();
            if(a.getNombre().equals(nombre)){
            
               ls.adifinal(a);
               a.getCant();
            }
         
            aux.adicola(a);
        }
        
  
        cl.vaciarCola(aux);
       
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
     
        Pedido ped = new Pedido();
        ColaMesa aux = new ColaMesa();
        System.out.println("*-*-*");
        System.out.println(cm.esVacia());
        
        while(!cm.esVacia()){
        
            Mesa mes = cm.elicola();
            if(mes.getId()==m){
                System.out.println("- aqui se añade el pedido al di "+m);
                ls.mostrar();
                mes.setPedido(ls);
            }
            aux.adicola(mes);
        }
        
        cm.vaciarCola(aux);
        res.setCMesa(cm);
        ped.Base(res);
        ped.Cargar(ls);
      
        ped.show();
        this.dispose();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Producto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Producto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
